const express=require("express");
const router=express.Router();
const wrapAsync = require("../utils/wrapAsync.js");
const userController=require("../controllers/user.js");
router.get("/signup",userController.rednderSignUp);
router.post("/signup",wrapAsync(userController.signup));
router.get("/login",userController.renderLogin);
router.post("/login",userController.login);
router.get("/logout",userController.logout);
router.get("/getUser/:userId",userController.fetchUser);
module.exports=router;